language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sanjeevt7301/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanjeevt7301/react-test npm test

  after_success:
    - docker build -t sanjeevt7301/multi-client ./client
    - docker build -t sanjeevt7301/multi-nginx ./nginx
    - docker build -t sanjeevt7301/multi-server ./server
    - docker build -t sanjeevt7301/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sanjeevt7301/multi-client
    - docker push sanjeevt7301/multi-nginx
    - docker push sanjeevt7301/multi-server
    - docker push sanjeevt7301/multi-worker